// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1gZ4zye8nsAehyZ6V7zUERq7cRLWi9OA',
    appId: '1:1037410255719:web:de089c1970c154374ea5c2',
    messagingSenderId: '1037410255719',
    projectId: 'cerboscan',
    authDomain: 'cerboscan.firebaseapp.com',
    storageBucket: 'cerboscan.firebasestorage.app',
    measurementId: 'G-0ZEP0YBGV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjXLuTbLhgMNWT1pshmXa9oh6_C76SpU',
    appId: '1:1037410255719:android:d46e425669bd0dea4ea5c2',
    messagingSenderId: '1037410255719',
    projectId: 'cerboscan',
    storageBucket: 'cerboscan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC77zquFZKHWKUURRy_Sa84zBJalvTICLY',
    appId: '1:1037410255719:ios:6e4e5bc361ac69f04ea5c2',
    messagingSenderId: '1037410255719',
    projectId: 'cerboscan',
    storageBucket: 'cerboscan.firebasestorage.app',
    iosBundleId: 'com.example.cerboscan',
  );
}
